import { Agent, WorkLog, OfficeRoom } from '../types/agent'

export const initialAgents: Agent[] = [
  {
    id: 'project-director',
    name: 'wLab:project-director',
    displayName: '專案總監',
    tier: 'leadership',
    status: 'working',
    currentTask: '審核本週研究進度報告',
    progress: 65,
    collaboratingWith: ['research-lead'],
    color: '#f59e0b',
    icon: '👔',
  },
  {
    id: 'research-lead',
    name: 'wLab:research-lead',
    displayName: '研究主管',
    tier: 'leadership',
    status: 'working',
    currentTask: '規劃下階段風能預測實驗',
    progress: 40,
    collaboratingWith: ['project-director', 'predictive-modeler'],
    color: '#f59e0b',
    icon: '🎯',
  },
  {
    id: 'predictive-modeler',
    name: 'wLab:predictive-modeler',
    displayName: '預測模型師',
    tier: 'ai-ml',
    status: 'working',
    currentTask: '訓練風速時序預測模型 (LSTM)',
    progress: 78,
    collaboratingWith: ['rag-architect'],
    color: '#8b5cf6',
    icon: '🤖',
  },
  {
    id: 'rag-architect',
    name: 'wLab:rag-architect',
    displayName: 'RAG 架構師',
    tier: 'ai-ml',
    status: 'waiting',
    currentTask: '等待文獻向量資料庫索引完成',
    progress: 92,
    color: '#8b5cf6',
    icon: '🔍',
  },
  {
    id: 'fault-diagnostician',
    name: 'wLab:fault-diagnostician',
    displayName: '故障診斷師',
    tier: 'ai-ml',
    status: 'idle',
    color: '#8b5cf6',
    icon: '🔧',
  },
  {
    id: 'paper-writer',
    name: 'wLab:paper-writer',
    displayName: '論文撰寫員',
    tier: 'research',
    status: 'working',
    currentTask: '撰寫風力發電預測論文第三章',
    progress: 55,
    collaboratingWith: ['literature-reviewer'],
    color: '#06b6d4',
    icon: '📝',
  },
  {
    id: 'literature-reviewer',
    name: 'wLab:literature-reviewer',
    displayName: '文獻審閱員',
    tier: 'research',
    status: 'completed',
    currentTask: '已完成 12 篇風能 ML 文獻摘要',
    color: '#06b6d4',
    icon: '📚',
  },
  {
    id: 'teaching-assistant',
    name: 'wLab:teaching-assistant',
    displayName: '教學助理',
    tier: 'research',
    status: 'idle',
    color: '#06b6d4',
    icon: '🎓',
  },
]

export const initialRooms: OfficeRoom[] = [
  {
    id: 'room-leadership',
    name: '總監室',
    tier: 'leadership',
    agents: initialAgents.filter((a) => a.tier === 'leadership'),
    icon: '🏛️',
    position: { row: 0, col: 0 },
  },
  {
    id: 'room-ai-ml',
    name: 'AI 研究室',
    tier: 'ai-ml',
    agents: initialAgents.filter((a) => a.tier === 'ai-ml'),
    icon: '🧠',
    position: { row: 0, col: 1 },
  },
  {
    id: 'room-research',
    name: '學術研究室',
    tier: 'research',
    agents: initialAgents.filter((a) => a.tier === 'research'),
    icon: '📖',
    position: { row: 1, col: 0 },
  },
]

export const initialWorkLogs: WorkLog[] = [
  {
    id: 'log-1',
    timestamp: new Date(Date.now() - 300000),
    agentId: 'predictive-modeler',
    agentName: '預測模型師',
    message: '開始訓練 LSTM 風速預測模型，使用過去 3 年數據',
    type: 'info',
  },
  {
    id: 'log-2',
    timestamp: new Date(Date.now() - 240000),
    agentId: 'literature-reviewer',
    agentName: '文獻審閱員',
    message: '完成 12 篇風能機器學習相關論文的摘要整理',
    type: 'success',
  },
  {
    id: 'log-3',
    timestamp: new Date(Date.now() - 180000),
    agentId: 'rag-architect',
    agentName: 'RAG 架構師',
    message: '向量資料庫索引進度 92%，等待剩餘文件處理',
    type: 'warning',
  },
  {
    id: 'log-4',
    timestamp: new Date(Date.now() - 120000),
    agentId: 'paper-writer',
    agentName: '論文撰寫員',
    message: '正在撰寫風力發電預測論文第三章：方法論',
    type: 'info',
  },
  {
    id: 'log-5',
    timestamp: new Date(Date.now() - 60000),
    agentId: 'project-director',
    agentName: '專案總監',
    message: '已收到本週進度報告，正在審核各團隊成果',
    type: 'info',
  },
  {
    id: 'log-6',
    timestamp: new Date(Date.now() - 30000),
    agentId: 'research-lead',
    agentName: '研究主管',
    message: '與預測模型師討論下階段實驗設計方案',
    type: 'info',
  },
]

export const tierColors: Record<string, { bg: string; border: string; accent: string }> = {
  leadership: {
    bg: 'bg-amber-950/30',
    border: 'border-amber-700/40',
    accent: 'text-amber-400',
  },
  'ai-ml': {
    bg: 'bg-violet-950/30',
    border: 'border-violet-700/40',
    accent: 'text-violet-400',
  },
  research: {
    bg: 'bg-cyan-950/30',
    border: 'border-cyan-700/40',
    accent: 'text-cyan-400',
  },
  data: {
    bg: 'bg-emerald-950/30',
    border: 'border-emerald-700/40',
    accent: 'text-emerald-400',
  },
  domain: {
    bg: 'bg-rose-950/30',
    border: 'border-rose-700/40',
    accent: 'text-rose-400',
  },
  engineering: {
    bg: 'bg-blue-950/30',
    border: 'border-blue-700/40',
    accent: 'text-blue-400',
  },
}

export const simulationTasks: Record<string, string[]> = {
  'project-director': [
    '審核本週研究進度報告',
    '分配新研究任務給各團隊',
    '與外部合作單位視訊會議',
    '彙整季度研究成果摘要',
  ],
  'research-lead': [
    '規劃下階段風能預測實驗',
    '審閱論文初稿並提供修改建議',
    '設計新的 benchmark 測試方案',
    '統整各研究員的數據分析結果',
  ],
  'predictive-modeler': [
    '訓練風速時序預測模型 (LSTM)',
    '調整 Transformer 模型超參數',
    '比較不同模型的 MAE 與 RMSE',
    '處理感測器異常數據清洗',
  ],
  'rag-architect': [
    '建構風能文獻向量資料庫',
    '優化檢索增強生成管線',
    '測試新的 embedding 模型效果',
    '整合多語言論文檢索功能',
  ],
  'fault-diagnostician': [
    '分析風機葉片振動異常訊號',
    '建立故障預測分類模型',
    '處理 SCADA 系統數據匯入',
    '生成設備健康狀態報告',
  ],
  'paper-writer': [
    '撰寫風力發電預測論文第三章',
    '修改論文引言與相關工作段落',
    '整理實驗結果圖表',
    '校對論文格式符合期刊要求',
  ],
  'literature-reviewer': [
    '搜尋最新風能 AI 相關論文',
    '整理論文摘要與重點比較表',
    '分析研究趨勢與技術缺口',
    '更新文獻資料庫分類標籤',
  ],
  'teaching-assistant': [
    '準備深度學習課程教材',
    '批改學生程式作業',
    '整理常見問題 FAQ 文件',
    '製作風能基礎知識簡報',
  ],
}

export const simulationLogMessages: Record<string, string[]> = {
  'project-director': [
    '已收到本週進度報告，正在審核各團隊成果',
    '已完成任務分配，通知相關成員',
    '外部合作會議結束，記錄重點事項',
    '季度報告彙整完成，準備提交',
  ],
  'research-lead': [
    '實驗設計初稿已完成，待團隊討論',
    '論文修改建議已回覆給撰寫員',
    'Benchmark 測試方案 v2 已定案',
    '各研究員數據已彙整至共享資料夾',
  ],
  'predictive-modeler': [
    'LSTM 模型 Epoch 50/100，當前 loss: 0.0032',
    '超參數搜尋完成，最佳學習率: 0.001',
    '模型評估完成：MAE=2.31, RMSE=3.15',
    '異常數據已清洗，共移除 127 筆記錄',
  ],
  'rag-architect': [
    '向量資料庫已新增 350 篇論文索引',
    'RAG 管線回應延遲優化至 1.2 秒',
    '新 embedding 模型測試：召回率提升 8%',
    '多語言檢索模組整合完成',
  ],
  'fault-diagnostician': [
    '偵測到 #7 號風機葉片異常振動頻率',
    '故障分類模型準確率達 94.7%',
    'SCADA 數據匯入完成，共 2.3M 筆記錄',
    '設備健康報告已生成並通知維護團隊',
  ],
  'paper-writer': [
    '第三章方法論段落初稿完成 (2,500 字)',
    '引言段落已根據審閱意見修改',
    '已產生 8 張實驗結果圖表',
    '論文格式檢查通過，符合期刊規範',
  ],
  'literature-reviewer': [
    '本週新增 15 篇相關論文至資料庫',
    '論文比較表已更新，涵蓋 2024-2025 年研究',
    '研究趨勢分析報告已完成',
    '文獻分類標籤已重新整理為 12 個類別',
  ],
  'teaching-assistant': [
    'CNN 章節教材投影片已完成 (45 頁)',
    '已批改 32 份學生作業，平均分 82.5',
    'FAQ 文件已更新，新增 8 個常見問題',
    '風能基礎簡報製作完成，共 30 頁',
  ],
}
